set(PROJECT_EXECUTABLE "" CACHE INTERNAL "")
set(PROJECT_BUILD_DIR "" CACHE INTERNAL "")

function(__add_executable NAME SOURCES)
   add_executable(${NAME} ${SOURCES})
   set(PROJECT_EXECUTABLE ${NAME} CACHE INTERNAL "")
   set(PROJECT_BUILD_DIR ${CMAKE_CURRENT_BINARY_DIR} CACHE INTERNAL "")
endfunction()